//go:build ignore
// +build ignore

// Command api_tool generates api.go from api_def.go. The command also has
// an option to compare api_def.go to Nvim's current API meta data.
package main

import (
	"flag"
	"go/ast"
	"go/token"
	"log"
	"strings"
	"text/template"
)

// APIInfo represents the output from nvim --api-info
type APIInfo struct {
	ErrorTypes map[string]ErrorType     `msgpack:"error_types"`
	Types      map[string]ExtensionType `msgpack:"types"`
	Functions  []*Function              `msgpack:"functions"`
	UIOptions  UIOptions                `msgpack:"ui_options"`
	Version    Version                  `msgpack:"version"`
}

type ErrorType struct {
	ID int `msgpack:"id"`
}

type ExtensionType struct {
	ID  int    `msgpack:"id"`
	Doc string `msgpack:"-"`
}

type Function struct {
	Name            string   `msgpack:"name"`
	Parameters      []*Field `msgpack:"parameters"`
	ReturnName      string   `msgpack:"_"`
	ReturnType      string   `msgpack:"return_type"`
	DeprecatedSince int      `msgpack:"deprecated_since"`
	Doc             string   `msgpack:"-"`
	GoName          string   `msgpack:"-"`
	ReturnPtr       bool     `msgpack:"-"`
}

type Field struct {
	Type string `msgpack:",array"`
	Name string
}

type UIOptions []string

type Version struct {
	APICompatible int  `msgpack:"api_compatible"`
	APILevel      int  `msgpack:"api_level"`
	APIPrerelease bool `msgpack:"api_prerelease"`
	Major         int  `msgpack:"major"`
	Minor         int  `msgpack:"minor"`
	Patch         int  `msgpack:"patch"`
}

var errorTypes = map[string]ErrorType{
	"Exception": {
		ID: 0,
	},
	"Validation": {
		ID: 1,
	},
}

var extensionTypes = map[string]ExtensionType{
	"Buffer": {
		ID:  0,
		Doc: `// Buffer represents a Nvim buffer.`,
	},
	"Window": {
		ID:  1,
		Doc: `// Window represents a Nvim window.`,
	},
	"Tabpage": {
		ID:  2,
		Doc: `// Tabpage represents a Nvim tabpage.`,
	},
}

func formatNode(fset *token.FileSet, node any) string { _ = "STUB: not implemented"; return "" }

func parseFields(fset *token.FileSet, fl *ast.FieldList) []*Field {
	_ = "STUB: not implemented"
	return nil
}

// parseAPIDef parses the file api_def.go.
func parseAPIDef() ([]*Function, []*Function, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}

const genTemplate = `

{{define "doc" -}}
{{.Doc}}
//
// See: [{{.Name}}()]
// 
// [{{.Name}}()]: https://neovim.io/doc/user/api.html#{{.Name}}()
{{- end}}

{{range .Functions}}
{{if eq "any" .ReturnType}}
{{template "doc" .}}
func (v *Nvim) {{.GoName}}({{range .Parameters}}{{.Name}} {{.Type}},{{end}} result any) error {
    return v.call("{{.Name}}", result, {{range .Parameters}}{{.Name}},{{end}})
}

{{template "doc" .}}
func (b *Batch) {{.GoName}}({{range .Parameters}}{{.Name}} {{.Type}},{{end}} result any) {
    b.call("{{.Name}}", &result, {{range .Parameters}}{{.Name}},{{end}})
}

{{else if and .ReturnName .ReturnPtr}}
{{template "doc" .}}
func (v *Nvim) {{.GoName}}({{range .Parameters}}{{.Name}} {{.Type}},{{end}}) ({{.ReturnName}} *{{.ReturnType}}, err error) {
	var result {{.ReturnType}}
	err = v.call("{{.Name}}", &result, {{range .Parameters}}{{.Name}},{{end}})
	return &result, err
}
{{template "doc" .}}
func (b *Batch) {{.GoName}}({{range .Parameters}}{{.Name}} {{.Type}},{{end}} {{.ReturnName}} *{{.ReturnType}}) {
    b.call("{{.Name}}", {{.ReturnName}}, {{range .Parameters}}{{.Name}},{{end}})
}

{{else if and (.ReturnName) (not .ReturnPtr)}}
{{template "doc" .}}
func (v *Nvim) {{.GoName}}({{range .Parameters}}{{.Name}} {{.Type}},{{end}}) ({{.ReturnName}} {{.ReturnType}}, err error) {
	err = v.call("{{.Name}}", &{{.ReturnName}}, {{range .Parameters}}{{.Name}},{{end}})
	return {{.ReturnName}}, err
}
{{template "doc" .}}
func (b *Batch) {{.GoName}}({{range .Parameters}}{{.Name}} {{.Type}},{{end}} {{.ReturnName}} *{{.ReturnType}}) {
    b.call("{{.Name}}", {{.ReturnName}}, {{range .Parameters}}{{.Name}},{{end}})
}
{{else if .ReturnType}}
{{template "doc" .}}
func (v *Nvim) {{.GoName}}({{range .Parameters}}{{.Name}} {{.Type}},{{end}}) ({{if .ReturnPtr}}*{{end}}{{.ReturnType}}, error) {
    var result {{.ReturnType}}
    err := v.call("{{.Name}}", &result, {{range .Parameters}}{{.Name}},{{end}})
    return {{if .ReturnPtr}}&{{end}}result, err
}
{{template "doc" .}}
func (b *Batch) {{.GoName}}({{range .Parameters}}{{.Name}} {{.Type}},{{end}} result *{{.ReturnType}}) {
    b.call("{{.Name}}", result, {{range .Parameters}}{{.Name}},{{end}})
}
{{else}}
{{template "doc" .}}
func (v *Nvim) {{.GoName}}({{range .Parameters}}{{.Name}} {{.Type}},{{end}}) error {
    return v.call("{{.Name}}", nil, {{range .Parameters}}{{.Name}},{{end}})
}
{{template "doc" .}}
func (b *Batch) {{.GoName}}({{range .Parameters}}{{.Name}} {{.Type}},{{end}}) {
    b.call("{{.Name}}", nil, {{range .Parameters}}{{.Name}},{{end}})
}
{{end}}
{{end}}
`

var implementationTemplate = template.Must(template.New("implementation").Funcs(template.FuncMap{
	"lower": strings.ToLower,
}).Parse(`// Code generated by running "go generate" in github.com/neovim/go-client/nvim. DO NOT EDIT.

package nvim

import (
    "fmt"

    "github.com/neovim/go-client/msgpack"
    "github.com/neovim/go-client/msgpack/rpc"
)

const (
    {{- range $name, $type := .ErrorTypes}}
    {{- lower $name}}Error = {{$type.ID}}
    {{  end -}}
)

func withExtensions() rpc.Option {
	return rpc.WithExtensions(msgpack.ExtensionMap{
{{- range $name, $type := .Types}}
		{{$type.ID}}: func(p []byte) (any, error) {
			x, err := decodeExt(p)
			return {{$name}}(x), err
		},
{{end -}}
	})
}

{{range $name, $type := .Types}}
{{$type.Doc}}
type {{$name}} int

// MarshalMsgPack implements msgpack.Marshaler.
func (x {{$name}}) MarshalMsgPack(enc *msgpack.Encoder) error {
	return enc.PackExtension({{$type.ID}}, encodeExt(int(x)))
}

// UnmarshalMsgPack implements msgpack.Unmarshaler.
func (x *{{$name}}) UnmarshalMsgPack(dec *msgpack.Decoder) error {
	n, err := unmarshalExt(dec, {{$type.ID}}, x)
	*x = {{$name}}(n)
	return err
}

// String returns a string representation of the {{$name}}.
func (x {{$name}}) String() string {
	return fmt.Sprintf("{{$name}}:%d", int(x))
}
{{end}}
` + genTemplate))

var deprecatedTemplate = template.Must(template.New("deprecated").Funcs(template.FuncMap{
	"lower": strings.ToLower,
}).Parse(`// Code generated by running "go generate" in github.com/neovim/go-client/nvim. DO NOT EDIT.

package nvim

// EmbedOptions specifies options for starting an embedded instance of Nvim.
//
// Deprecated: Use ChildProcessOption instead.
type EmbedOptions struct {
	// Logf log function for rpc.WithLogf.
	Logf func(string, ...any)

	// Dir specifies the working directory of the command. The working
	// directory in the current process is used if Dir is "".
	Dir string

	// Path is the path of the command to run. If Path = "", then
	// StartEmbeddedNvim searches for "nvim" on $PATH.
	Path string

	// Args specifies the command line arguments. Do not include the program
	// name (the first argument) or the --embed option.
	Args []string

	// Env specifies the environment of the Nvim process. The current process
	// environment is used if Env is nil.
	Env []string
}

// NewEmbedded starts an embedded instance of Nvim using the specified options.
//
// The application must call Serve() to handle RPC requests and responses.
//
// Deprecated: Use NewChildProcess instead.
func NewEmbedded(options *EmbedOptions) (*Nvim, error) {
	if options == nil {
		options = &EmbedOptions{}
	}
	path := options.Path
	if path == "" {
		path = "nvim"
	}

	return NewChildProcess(
		ChildProcessArgs(append([]string{"--embed"}, options.Args...)...),
		ChildProcessCommand(path),
		ChildProcessEnv(options.Env),
		ChildProcessDir(options.Dir),
		ChildProcessServe(false))
}

// ExecuteLua executes a Lua block.
//
// Deprecated: Use ExecLua instead.
func (v *Nvim) ExecuteLua(code string, result any, args ...any) error {
	if args == nil {
		args = emptyArgs
	}
	return v.call("nvim_execute_lua", result, code, args)
}

// ExecuteLua executes a Lua block.
//
// Deprecated: Use ExecLua instead.
func (b *Batch) ExecuteLua(code string, result any, args ...any) {
	if args == nil {
		args = emptyArgs
	}
	b.call("nvim_execute_lua", result, code, args)
}
` + genTemplate))

func printImplementation(functions []*Function, tmpl *template.Template, outFile string) error {
	_ = "STUB: not implemented"
	return nil
}

func readAPIInfo(cmdName string) (*APIInfo, error) { _ = "STUB: not implemented"; return nil, nil }

// nvimTypes maps Go types to Nvim API types.
var nvimTypes = map[string]string{
	"":        "void",
	"[]byte":  "String",
	"[]uint":  "Array",
	"[]any":   "Array",
	"bool":    "Boolean",
	"int":     "Integer",
	"any":     "Object",
	"string":  "String",
	"float64": "Float",

	"ClientType":  "String",
	"Process":     "Object",
	"UserCommand": "Object",

	"Cmd":                         "Dictionary",
	"*Cmd":                        "Dictionary",
	"Channel":                     "Dictionary",
	"*Channel":                    "Dictionary",
	"ClientVersion":               "Dictionary",
	"HLAttrs":                     "Dictionary",
	"*HLAttrs":                    "Dictionary",
	"[]*HLAttrs":                  "Dictionary",
	"WindowConfig":                "Dictionary",
	"*WindowConfig":               "Dictionary",
	"ClientAttributes":            "Dictionary",
	"ClientMethods":               "Dictionary",
	"map[string]*ClientMethod":    "Dictionary",
	"map[string]*Command":         "Dictionary",
	"map[string][]string":         "Dictionary",
	"map[string]bool":             "Dictionary",
	"map[string]int":              "Dictionary",
	"map[string]any":              "Dictionary",
	"map[string]OptionValueScope": "Dictionary",
	"Mode":                        "Dictionary",
	"OptionInfo":                  "Dictionary",

	"[]*AutocmdType": "Array",
	"[]*Channel":     "Array",
	"[]*Process":     "Array",
	"[]*UI":          "Array",
	"[]ExtMark":      "Array",
	"[]TextChunk":    "Array",
	"Mark":           "Array",

	"[2]int":     "ArrayOf(Integer, 2)",
	"[]*Mapping": "ArrayOf(Dictionary)",
	"[][]byte":   "ArrayOf(String)",
	"[]Buffer":   "ArrayOf(Buffer)",
	"[]int":      "ArrayOf(Integer)",
	"[]string":   "ArrayOf(String)",
	"[]Tabpage":  "ArrayOf(Tabpage)",
	"[]Window":   "ArrayOf(Window)",
}

func convertToNvimTypes(f *Function) *Function { _ = "STUB: not implemented"; return nil }

type byName []*Function

func (a byName) Len() int           { _ = "STUB: not implemented"; return 0 }
func (a byName) Swap(i, j int)      { _ = "STUB: not implemented"; return }
func (a byName) Less(i, j int) bool { _ = "STUB: not implemented"; return false }

var compareTemplate = template.Must(template.New("").Funcs(template.FuncMap{
	"lower": strings.ToLower,
}).Parse(`
{{- range .Extra}}< {{template "f" .}}{{end}}
{{- range .Missing}}> {{template "f" .}}{{end}}
{{- range .Different}}----
< {{template "f" index . 0}}> {{template "f" index . 1}}{{end}}
{{- define "f"}}{{.Name}}({{range $i, $p := .Parameters}}{{if $i}}, {{end}}{{$p.Name}} {{$p.Type}}{{end}}){{with .ReturnType}} {{.}}{{end}}
    {{- print " {"}} name({{.Name}}){{with .DeprecatedSince}}; deprecatedSince({{.}});{{end}}{{print " }"}}
{{end}}`))

// hiddenAPIs list of hidden API.
var hiddenAPIs = map[string]bool{
	"nvim__set_hl_ns": true,
}

// specialAPIs lists API calls that are implemented by hand.
var specialAPIs = map[string]bool{
	"nvim_call_atomic":             true,
	"nvim_call_function":           true,
	"nvim_call_dict_function":      true,
	"nvim_execute_lua":             true,
	"nvim_exec_lua":                true,
	"nvim_buf_call":                true,
	"nvim_set_decoration_provider": true,
	"nvim_chan_send":               true, // FUNC_API_LUA_ONLY
	"nvim_win_call":                true, // FUNC_API_LUA_ONLY
	"nvim_notify":                  true, // implements underling nlua(vim.notify)
	"nvim_get_option_info":         true, // deprecated
}

func compareFunctions(cmdName string, functions []*Function) error {
	_ = "STUB: not implemented"
	return nil
}

func dumpAPI(cmdName string) error { _ = "STUB: not implemented"; return nil }

var (
	flagNvim       string
	flagGenerate   string
	flagDeprecated string
	flagCompare    bool
	flagDump       bool
)

func main() {
	log.SetFlags(log.Lshortfile)

	flag.StringVar(&flagNvim, "nvim", "nvim", "nvim binary path")
	flag.StringVar(&flagGenerate, "generate", "", "Generate implementation from api_def.go and write to `file`")
	flag.StringVar(&flagDeprecated, "deprecated", "", "Generate deprecated implementation from api_def.go and write to `file`")
	flag.BoolVar(&flagCompare, "compare", false, "Compare api_def.go to the output of nvim --api-info")
	flag.BoolVar(&flagDump, "dump", false, "Print nvim --api-info as JSON")
	flag.Parse()

	if flagDump {
		if err := dumpAPI(flagNvim); err != nil {
			log.Fatal(err)
		}
		return
	}

	functions, deprecated, err := parseAPIDef()
	if err != nil {
		log.Fatal(err)
	}

	switch {
	case flagCompare:
		functions = append(functions, deprecated...)
		if err := compareFunctions(flagNvim, functions); err != nil {
			log.Fatal(err)
		}

	case flagGenerate != "":
		if flagDeprecated == "" {
			functions = append(functions, deprecated...)
		}
		if err := printImplementation(functions, implementationTemplate, flagGenerate); err != nil {
			log.Fatal(err)
		}

		if flagDeprecated != "" {
			if err := printImplementation(deprecated, deprecatedTemplate, flagDeprecated); err != nil {
				log.Fatal(err)
			}
		}
	}
}
